spring:
   profiles:
      active: dev
---
# common: spring boot configuration
spring: 

   # devtools - live reload
   livereload:
      enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(Internationalization)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8

   # multipart
   multipart:
       enabled: true
       max-file-size: 50MB
       max-request-size: 50MB

   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true
---

#dev profile: spring boot configuration
spring:
   config:
      activate:
          on-profile: dev

   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.52:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: webdb
      password: webdb
      
      #hikari dbcp 히카리라는 이름으로 달려있음   initialSize->minimum-idle, maxActive->maximum-pool-size
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
---
# production profile: spring boot configuration
spring:
   config:
      activate:
          on-profile: production

   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://211.14.5.6:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: webdb
      password: webdbghdfdf
      
      #hikari dbcp 히카리라는 이름으로 달려있음   initialSize->minimum-idle, maxActive->maximum-pool-size
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
---

---
# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true
         force: false
         force-request: false
         force-response: false
   
---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
---
# logging
#개발할때의 dB와 Release할때의 DB다를 수 있음 
logging: 
   config: classpath:logback.xml
